_target_: consistency_policy.baseline.train_diffusion_unet_hybrid_workspace.TrainDiffusionUnetHybridWorkspace
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-train_loss={train_loss:.6f}.ckpt
    k: 5
    mode: max
    monitor_key: train_loss
dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: true
dataset_obs_steps: 2
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
horizon: 16
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: 2022.12.29-22.31.30_train_diffusion_unet_hybrid_square_image
  project: diffusion_policy_debug
  resume: true
  tags:
  - train_diffusion_unet_hybrid
  - square_image
  - default
multi_run:
  run_dir: data/outputs/2022.12.29/22.31.30_train_diffusion_unet_hybrid_square_image
  wandb_name_base: 2022.12.29-22.31.30_train_diffusion_unet_hybrid_square_image
n_action_steps: 8
n_latency_steps: 0
n_obs_steps: 2
name: train_diffusion_unet_hybrid
obs_as_global_cond: true
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-06
past_action_visible: false
policy:
  _target_: diffusion_policy.policy.diffusion_unet_hybrid_image_policy.DiffusionUnetHybridImagePolicy
  cond_predict_scale: true
  crop_shape: null
  diffusion_step_embed_dim: 128
  down_dims:
  - 512
  - 1024
  - 2048
  eval_fixed_crop: true
  horizon: 16
  kernel_size: 5
  n_action_steps: 8
  n_groups: 8
  n_obs_steps: 2
  noise_scheduler:
    # _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
    # beta_end: 0.02
    # beta_schedule: squaredcos_cap_v2
    # beta_start: 0.0001
    # clip_sample: true
    # num_train_timesteps: 100
    # prediction_type: epsilon
    # variance_type: fixed_small
    _target_: diffusers.schedulers.scheduling_ddim.DDIMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    clip_sample: True
    set_alpha_to_one: True
    steps_offset: 0
    prediction_type: epsilon # or sample
  num_inference_steps: 15
  obs_as_global_cond: true
  obs_encoder_group_norm: true
  shape_meta:
    action:
      shape:
      - 13
    obs:
      base_pose:
        shape:
        - 3
      arm_pos:
        shape:
        - 3
      arm_quat:
        shape:
        - 4
      gripper_pos:
        shape:
        - 1
      base_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      wrist_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
shape_meta:
  action:
    shape:
    - 13
  obs:
    base_pose:
      shape:
      - 3
    arm_pos:
      shape:
      - 3
    arm_quat:
      shape:
      - 4
    gripper_pos:
      shape:
      - 1
    base_image:
      shape:
      - 3
      - 84
      - 84
      type: rgb
    wrist_image:
      shape:
      - 3
      - 84
      - 84
      type: rgb
task:
  abs_action: true
  dataset:
    _target_: consistency_policy.6Dpos_dataset.RobomimicReplayImageDataset
    abs_action: true
    dataset_path: data/jimmy/demos-microwave-v5.hdf5
    horizon: 16
    n_obs_steps: 2
    pad_after: 7
    pad_before: 1
    rotation_rep: rotation_6d
    seed: 42
    shape_meta:
      action:
        shape:
        - 13
      obs:
        base_pose:
          shape:
          - 3
        arm_pos:
          shape:
          - 3
        arm_quat:
          shape:
          - 4
        gripper_pos:
          shape:
          - 1
        base_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        wrist_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
    use_cache: true
    val_ratio: 0.02
  dataset_path: data/jimmy/demos-microwave-v5.hdf5
  dataset_type: ph
  env_runner:
    _target_: diffusion_policy.env_runner.robomimic_image_runner.RobomimicImageRunner
    abs_action: true
    crf: 22
    dataset_path: data/jimmy/demos-microwave-v5.hdf5
    fps: 10
    max_steps: 400
    n_action_steps: 8
    n_envs: 28
    n_obs_steps: 2
    n_test: 28
    n_test_vis: 4
    n_train: 6
    n_train_vis: 2
    past_action: false
    render_obs_key: agentview_image
    shape_meta:
      action:
        shape:
        - 13
      obs:
        base_pose:
          shape:
          - 3
        arm_pos:
          shape:
          - 3
        arm_quat:
          shape:
          - 4
        gripper_pos:
          shape:
          - 1
        base_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
        wrist_image:
          shape:
          - 3
          - 84
          - 84
          type: rgb
    test_start_seed: 100000
    tqdm_interval_sec: 1.0
    train_start_idx: 0
  name: jimmy_image
  shape_meta:
    action:
      shape:
      - 13
    obs:
      base_pose:
        shape:
        - 3
      arm_pos:
        shape:
        - 3
      arm_quat:
        shape:
        - 4
      gripper_pos:
        shape:
        - 1
      base_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
      wrist_image:
        shape:
        - 3
        - 84
        - 84
        type: rgb
  task_name: jimmy
task_name: jimmy_image
training:
  checkpoint_every: 100
  inference_mode: false
  online_rollouts: false
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 8000
  resume: true
  resume_path: /juno/u/aadityap/Consistency-Accelerated-Policy-Networks/outputs/ddim/jimmy_microwave84v5large/checkpoints/epoch_300.ckpt
  rollout_every: 50
  sample_every: 5
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1000000
  val_sample_every: 5000000
  num_evaluate_steps: 15
  output_dir: outputs/ddim/jimmy
val_dataloader:
  batch_size: 64
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false